package Manu.Hadoop;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;



public class display extends javax.swing.JFrame {

    /**
     * Creates new form display
     */
    public display() {
        initComponents();
 //Start Flag
 	   
 	   try 
 	   {
 		WordCount.main();
 		WordCount2.main();
		WordCount_list.main();
 	   } 
 	   catch (Exception e1) {e1.printStackTrace();}
 	   
 	   String t1="";
 	   String t2="";
 	   String t3="";
 	   int flag=0;
 	   String FILENAME = "output/part-r-00000";	  
 	   String FILENAME2 = "output3/part-r-00000";			  	  
 	   String FILENAME3 = "output2/part-r-00000";			  	  	   
 	   BufferedReader br = null;
 	   FileReader fr = null;
 	   BufferedReader br2 = null;
 	   FileReader fr2 = null;
 	   BufferedReader br3 = null;
 	   FileReader fr3 = null;			 	  
 	 	
 	  try {
 			fr = new FileReader(FILENAME);
 			br = new BufferedReader(fr);
 			br = new BufferedReader(new FileReader(FILENAME));
 			String sCurrentLine="";
 			while ((sCurrentLine = br.readLine()) != null)
 			{				
 				String[] parts = sCurrentLine.split("	");
 				String part1 = parts[0]; // IP
 				String part2 = parts[1];//Date
 				//System.out.println(sCurrentLine);
 				//System.out.println("1");
 			    if(part2.length()>20)
 			    {
 			    fr2 = new FileReader(FILENAME2);
 			 	br2 = new BufferedReader(fr2);
 			 	br2 = new BufferedReader(new FileReader(FILENAME2));
 			 	String sCurrentLine2="";
 			 	while ((sCurrentLine2 = br2.readLine()) != null)
 			 		{
 			 			String[] pts = sCurrentLine2.split("	");
 			 			String pt1 = pts[0]; //Hash 
 			 			String pt2 = pts[1]; //IP
 			 			//System.out.println("2");
 			            if(pt2.equals(part1))
 			            {
 			            	fr3 = new FileReader(FILENAME3);
 			 			 	br3 = new BufferedReader(fr3);
 			 			 	br3 = new BufferedReader(new FileReader(FILENAME3));
 			 			 	String sCurrentLine3="";
 			 			 	while ((sCurrentLine3 = br3.readLine()) != null)
 			 			 		{
 			 			 			String[] prts = sCurrentLine3.split("	");
 			 			 			String prt1 = prts[0]; //Hash 
 			 			 			String prt2 = prts[1]; //Date
 			 			 			//System.out.println("3");
 			 			 			if(prt2.length()==part2.length())
 			 			 			{	
 			 			 				System.out.println("SPAM Detected");
 			 			 				display.append("SPAM Detected \n");
 			 			 				t1=prt1;
 			 			 				t2=prt2;
 			 			 				t3=pt2;
 			 			 				display.append(t1+"  "+t2+"  "+t3+"  \n");
 			 			 				System.out.println(t1+"  "+t2+"  "+t3+" ");
 			 			 				flag=1;			 			 				
 			 			 				break;
 			 			 			}			 			 		
 			 			 		}					 		
 			 			 	if(flag==1)
 			 					break;
 			            }
 			       }
 			    }
 			}			    
 		} catch (IOException e) {
 			e.printStackTrace();
 		} finally {
 			try {
 				if (br != null)
 					br.close();
 				if (fr != null)
 					fr.close();

 			} catch (IOException ex) {

 				ex.printStackTrace();
 			}
 		}
    
    
//End Flag    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        display.setColumns(20);
        display.setRows(5);
        jScrollPane1.setViewportView(display);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("SPAM DETECTION RESULTS");

        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("MAIN MENU");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        dispose();
		String[] args = new String[3];
		args[0] = "output";
		DeleteDir.main(args);
		String[] args2 = new String[3];
		args2[0] = "output2";
		DeleteDir.main(args2);
		String[] args3 = new String[3];
		args3[0] = "output3";
		DeleteDir.main(args3);
    }                                        
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	adminpanel any = new adminpanel();
		any.setVisible(true);
		dispose();
		String[] args = new String[3];
		args[0] = "output";
		DeleteDir.main(args);
		String[] args2 = new String[3];
		args2[0] = "output2";
		DeleteDir.main(args2);
		String[] args3 = new String[3];
		args3[0] = "output3";
		DeleteDir.main(args3);

    }                   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new display().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextArea display;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}